global using CommonBasicLibraries.CollectionClasses;
global using QuestTesterLibrary.Extensions;
global using AOEOBasicDataLibrary.Services;
global using QuestTesterLibrary.Services;
global using dd1 = AOEOBasicDataLibrary.Helpers.BasicGameLocationHelpers;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using System.Xml.Linq;
global using AOEOQuestEngine.CoreLibrary.Shared.Containers;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using AOEOQuestEngine.CoreLibrary.Shared.Interfaces;
global using AOEOTechEditorLibrary.Techs;
global using AOEOTechEditorLibrary.Prereqs;
global using AOEOTechEditorLibrary.Effects;
global using AOEOQuestEngine.CoreLibrary.Shared.Models;
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using AOEOTechEditorLibrary.Helpers;
global using AOEOCivilizationLibrary.ApplicationState;
global using Microsoft.Extensions.DependencyInjection;
global using AOEOCivilizationLibrary.DataServices;
global using AOEOBasicDataLibrary.Helpers;
global using AOEOCivilizationLibrary.Models;
global using AOEOQuestEngine.CoreLibrary.Shared.Services;
global using AOEOQuestEngine.CoreLibrary.Shared.Extensions;
global using AOEOQuestEngine.CoreLibrary.ChampionMode.Extensions;
global using AOEOQuestEngine.CoreLibrary.ChampionMode.Services;
global using Microsoft.AspNetCore.Components;
global using ll1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileLocator;
global using AOEOCivilizationLibrary.ViewModels;
global using AOEOQuestEngine.CoreLibrary.Shared.Configurations;
global using QuestTesterLibrary.ViewModels;
global using AOEOQuestEngine.CoreLibrary.ChampionMode.ViewModels;
global using uu1 = AOEOBasicDataLibrary.Helpers.UnitGroupConstants;
global using oo1 = AOEOTechEditorLibrary.Prereqs.TechConditionOperators;
global using CommonBasicLibraries.BasicUIProcesses;
global using AOEOTechEditorLibrary.Shared;
global using AOEOTechEditorLibrary.Services;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.Misc;
global using js1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.JsonSerializers.FileHelpers;
global using AOEOQuestEngine.CoreLibrary.StandardMode.Services;
global using AOEOQuestEngine.CoreLibrary.StandardMode.Extensions;
global using CommonBasicLibraries.BasicDateTimeProcesses;
