global using CommonBasicLibraries.CollectionClasses;
global using QuestTesterLibrary.Extensions;
global using AOEOBasicDataLibrary.Services;
global using QuestTesterLibrary.LocatorServices;
global using dd1 = AOEOBasicDataLibrary.Helpers.BasicGameLocationHelpers;
global using CommonBasicLibraries.BasicDataSettingsAndProcesses;
global using System.Xml.Linq;
global using AOEOQuestEngine.CoreLibrary.Shared.Containers;
global using CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.BasicExtensions;
global using AOEOQuestEngine.CoreLibrary.Shared.Interfaces;
global using AOEOTechEditorLibrary.Models;
global using AOEOQuestEngine.CoreLibrary.Shared.Models;
global using ff1 = CommonBasicLibraries.AdvancedGeneralFunctionsAndProcesses.FileFunctions.FileFunctions;
global using AOEOTechEditorLibrary.Helpers;
global using AOEOCivilizationLibrary.ApplicationState;
global using Microsoft.Extensions.DependencyInjection;
global using AOEOCivilizationLibrary.DataServices;
global using AOEOBasicDataLibrary.Helpers;
global using AOEOCivilizationLibrary.Models;
global using AOEOQuestEngine.CoreLibrary.Shared.Services;
global using AOEOQuestEngine.CoreLibrary.Shared.Extensions;
global using AOEOQuestEngine.CoreLibrary.ChampionMode.Extensions;
global using AOEOQuestEngine.CoreLibrary.ChampionMode.Services;
